# Generated by Django 5.1.3 on 2025-06-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_order_customer_name_sales_source_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory_management.order'),
        ),
    ]
