# Generated by Django 5.1.3 on 2025-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_fishstock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishstock',
            name='fish_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('order', 'From Order'), ('middle_men', 'Middle Men'), ('direct', 'Direct Sale')], default='manual', max_length=50),
        ),
    ]
