# Generated by Django 5.1.3 on 2025-06-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_fishstock_fish_size_orderitem_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_management.fishstock'),
        ),
    ]
